// Generated by tools/gen_keymap.py from Linux include/dt-bindings/input/cros-ec-keyboard.h. Do not edit.
// Chrome EC keyboard matrix (8 rows x 13 columns) -> ASCII, US layout.
#define KB_ROWS 8
#define KB_COLS 13
#define KB_SHIFT 1
#define KB_CTRL 2
#define KB_ALT 3
#define KB_SEARCH 4
#define K_UP 129
#define K_DOWN 130
#define K_LEFT 131
#define K_RIGHT 132
#define K_F1 144   /* F1..F10 = K_F1 .. K_F1+9 */
static const char kb_norm[KB_ROWS][KB_COLS] = {
    {0, 4, 144, 'b', 153, 0, 'n', 0, '=', 0, 3, 0, 0},
    {0, 27, 147, 'g', 150, 0, 'h', 0, '\'', 152, 0, '\b', 0},
    {2, '\t', 146, 't', 149, ']', 'y', 0, '[', 151, 0, 0, 0},
    {4, '`', 145, '5', 148, 0, '6', 0, '-', 0, 0, '\\', 0},
    {2, 'a', 'd', 'f', 's', 'k', 'j', 0, ';', 'l', '\\', '\n', 0},
    {0, 'z', 'c', 'v', 'x', ',', 'm', 1, '/', '.', 0, ' ', 0},
    {0, '1', '3', '4', '2', '8', '7', 0, '0', '9', 3, 130, 132},
    {0, 'q', 'e', 'r', 'w', 'i', 'u', 1, 'p', 'o', 0, 129, 131},
};
static const char kb_shift[KB_ROWS][KB_COLS] = {
    {0, 4, 144, 'B', 153, 0, 'N', 0, '+', 0, 3, 0, 0},
    {0, 27, 147, 'G', 150, 0, 'H', 0, '"', 152, 0, '\b', 0},
    {2, '\t', 146, 'T', 149, '}', 'Y', 0, '{', 151, 0, 0, 0},
    {4, '~', 145, '%', 148, 0, '^', 0, '_', 0, 0, '|', 0},
    {2, 'A', 'D', 'F', 'S', 'K', 'J', 0, ':', 'L', '|', '\n', 0},
    {0, 'Z', 'C', 'V', 'X', '<', 'M', 1, '?', '>', 0, ' ', 0},
    {0, '!', '#', '$', '@', '*', '&', 0, ')', '(', 3, 130, 132},
    {0, 'Q', 'E', 'R', 'W', 'I', 'U', 1, 'P', 'O', 0, 129, 131},
};
