// Generated by tools/gen_keymap.py from Linux include/dt-bindings/input/cros-ec-keyboard.h. Do not edit.
// Chrome EC keyboard matrix (8 rows x 13 columns) -> ASCII, US layout.
#define KB_ROWS 8
#define KB_COLS 13
#define KB_SHIFT 1
#define KB_CTRL 2
#define KB_ALT 3
#define KB_SEARCH 4
static const char kb_norm[KB_ROWS][KB_COLS] = {
    {0, 4, 0, 'b', 0, 0, 'n', 0, '=', 0, 3, 0, 0},
    {0, 27, 0, 'g', 0, 0, 'h', 0, '\'', 0, 0, '\b', 0},
    {2, '\t', 0, 't', 0, ']', 'y', 0, '[', 0, 0, 0, 0},
    {4, '`', 0, '5', 0, 0, '6', 0, '-', 0, 0, '\\', 0},
    {2, 'a', 'd', 'f', 's', 'k', 'j', 0, ';', 'l', '\\', '\n', 0},
    {0, 'z', 'c', 'v', 'x', ',', 'm', 1, '/', '.', 0, ' ', 0},
    {0, '1', '3', '4', '2', '8', '7', 0, '0', '9', 3, 0, 0},
    {0, 'q', 'e', 'r', 'w', 'i', 'u', 1, 'p', 'o', 0, 0, 0},
};
static const char kb_shift[KB_ROWS][KB_COLS] = {
    {0, 4, 0, 'B', 0, 0, 'N', 0, '+', 0, 3, 0, 0},
    {0, 27, 0, 'G', 0, 0, 'H', 0, '"', 0, 0, '\b', 0},
    {2, '\t', 0, 'T', 0, '}', 'Y', 0, '{', 0, 0, 0, 0},
    {4, '~', 0, '%', 0, 0, '^', 0, '_', 0, 0, '|', 0},
    {2, 'A', 'D', 'F', 'S', 'K', 'J', 0, ':', 'L', '|', '\n', 0},
    {0, 'Z', 'C', 'V', 'X', '<', 'M', 1, '?', '>', 0, ' ', 0},
    {0, '!', '#', '$', '@', '*', '&', 0, ')', '(', 3, 0, 0},
    {0, 'Q', 'E', 'R', 'W', 'I', 'U', 1, 'P', 'O', 0, 0, 0},
};
