#!/usr/bin/env python3
"""Generate the Chromebook keyboard tables from the Linux sources (run in WSL):
    python3 tools/gen_keymap.py ~/work/linux
Writes keymap.h (for wave-os) and fakehana/keymap.py (for the fake EC) from
include/dt-bindings/input/cros-ec-keyboard.h (CROS_STD_TOP_ROW_KEYMAP + CROS_STD_MAIN_KEYMAP).
"""
import os, re, sys

ROWS, COLS = 8, 13
SHIFT, CTRL, ALT, SEARCH = 1, 2, 3, 4          # modifier markers in the "normal" table

# US layout: KEY_* name -> (normal, shifted)
PAIRS = {'GRAVE': '`~', 'MINUS': '-_', 'EQUAL': '=+', 'LEFTBRACE': '[{', 'RIGHTBRACE': ']}',
         'BACKSLASH': '\\|', 'SEMICOLON': ';:', 'APOSTROPHE': '\'"', 'COMMA': ',<', 'DOT': '.>', 'SLASH': '/?'}
DIGITS = dict(zip('1234567890', '!@#$%^&*()'))

def chars(name):
    if len(name) == 1 and name.isalpha():
        return name.lower(), name.upper()
    if len(name) == 1 and name.isdigit():
        return name, DIGITS[name]
    if name in PAIRS:
        return PAIRS[name][0], PAIRS[name][1]
    return {'SPACE': (' ', ' '), 'ENTER': ('\n', '\n'), 'BACKSPACE': ('\b', '\b'), 'TAB': ('\t', '\t'),
            'ESC': ('\x1b', '\x1b'),
            'LEFTSHIFT': (chr(SHIFT),) * 2, 'RIGHTSHIFT': (chr(SHIFT),) * 2,
            'LEFTCTRL': (chr(CTRL),) * 2, 'RIGHTCTRL': (chr(CTRL),) * 2,
            'LEFTALT': (chr(ALT),) * 2, 'RIGHTALT': (chr(ALT),) * 2,
            'LEFTMETA': (chr(SEARCH),) * 2}.get(name, ('\0', '\0'))

def main():
    linux = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/work/linux')
    src = open(os.path.join(linux, 'include/dt-bindings/input/cros-ec-keyboard.h')).read()
    keys = {}
    for macro in ('CROS_STD_TOP_ROW_KEYMAP', 'CROS_STD_MAIN_KEYMAP'):
        body = re.search(r'#define %s\s*\\\n(.*?)(?:\n\s*\n|\n#)' % macro, src, re.S).group(1)
        for r, c, k in re.findall(r'MATRIX_KEY\((0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+),\s*KEY_(\w+)\)', body):
            keys[(int(r, 16), int(c, 16))] = k
    norm = [['\0'] * COLS for _ in range(ROWS)]
    shift = [['\0'] * COLS for _ in range(ROWS)]
    names = [[''] * COLS for _ in range(ROWS)]
    for (r, c), k in keys.items():
        norm[r][c], shift[r][c] = chars(k)
        names[r][c] = k

    def cstr(ch):
        return {'\n': "'\\n'", '\b': "'\\b'", '\t': "'\\t'", '\x1b': '27', '\\': "'\\\\'", "'": "'\\''", '\0': '0'}.get(
            ch, str(ord(ch)) if ord(ch) < 32 else "'%s'" % ch)

    out = ['// Generated by tools/gen_keymap.py from Linux include/dt-bindings/input/cros-ec-keyboard.h. Do not edit.',
           '// Chrome EC keyboard matrix (%d rows x %d columns) -> ASCII, US layout.' % (ROWS, COLS),
           '#define KB_ROWS %d' % ROWS, '#define KB_COLS %d' % COLS,
           '#define KB_SHIFT %d' % SHIFT, '#define KB_CTRL %d' % CTRL, '#define KB_ALT %d' % ALT, '#define KB_SEARCH %d' % SEARCH]
    for name, tbl in (('kb_norm', norm), ('kb_shift', shift)):
        out.append('static const char %s[KB_ROWS][KB_COLS] = {' % name)
        for r in range(ROWS):
            out.append('    {' + ', '.join(cstr(tbl[r][c]) for c in range(COLS)) + '},')
        out.append('};')
    here = os.path.dirname(os.path.abspath(__file__))
    open(os.path.join(here, '..', 'keymap.h'), 'w', newline='\n').write('\n'.join(out) + '\n')

    py = ['# Generated by tools/gen_keymap.py. Do not edit.', 'ROWS, COLS = %d, %d' % (ROWS, COLS),
          '# (row, col) -> Linux key name', 'KEYS = {']
    for (r, c) in sorted(keys):
        py.append('    (%d, %d): %r,' % (r, c, keys[(r, c)]))
    py.append('}')
    py.append('NORM = %r' % [''.join(row) for row in norm])
    py.append('SHIFTED = %r' % [''.join(row) for row in shift])
    open(os.path.join(here, '..', 'fakehana', 'keymap.py'), 'w', newline='\n').write('\n'.join(py) + '\n')
    print('keys mapped: %d' % len(keys))

if __name__ == '__main__':
    main()
