# Turns DejaVu Sans (free font, from WSL /usr/share/fonts) into smooth (anti-aliased) bitmaps for the graphical browser: font_aa.h.
# Sizes in pixels, regular + bold, plus DejaVu Sans Mono for <pre>/<code>. Characters 32..126. Each glyph: 8-bit coverage, its box and advance.
param([int[]]$Sizes = @(13, 15, 18, 22, 28, 36))
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference = 'Stop'
$wsl = '\\wsl.localhost\Ubuntu\usr\share\fonts\truetype\dejavu'
$files = @{ 'sans' = 'DejaVuSans.ttf'; 'bold' = 'DejaVuSans-Bold.ttf'; 'mono' = 'DejaVuSansMono.ttf' }
$pfc = New-Object System.Drawing.Text.PrivateFontCollection
$tmp = Join-Path $env:TEMP 'wave-fonts'; New-Item -ItemType Directory -Force -Path $tmp | Out-Null
foreach ($k in $files.Keys) { Copy-Item (Join-Path $wsl $files[$k]) (Join-Path $tmp $files[$k]) -Force; $pfc.AddFontFile((Join-Path $tmp $files[$k])) }
$fam = @{}; foreach ($f in $pfc.Families) { $fam[$f.Name] = $f }

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('// Generated by tools/make_fonts.ps1 from DejaVu Sans / DejaVu Sans Mono (Bitstream Vera license: free to use and redistribute). Do not edit.')
[void]$out.AppendLine('// For each face: line height, ascent, then per character (32..126): advance, glyph left offset, top offset, width, height, offset of its coverage bytes.')
[void]$out.AppendLine('struct aaglyph { unsigned char adv; signed char x; unsigned char y, w, h; unsigned int off; };')
[void]$out.AppendLine('struct aaface { unsigned char size, line, ascent, bold, mono; const struct aaglyph *g; const unsigned char *bits; };')
$faces = @()
$fi = 0
foreach ($kind in @('sans', 'bold', 'mono')) {
    foreach ($px in $Sizes) {
        if ($kind -eq 'mono' -and $px -gt 18) { continue }
        $famName = if ($kind -eq 'mono') { 'DejaVu Sans Mono' } else { 'DejaVu Sans' }
        $style = if ($kind -eq 'bold') { [System.Drawing.FontStyle]::Bold } else { [System.Drawing.FontStyle]::Regular }
        $font = New-Object System.Drawing.Font $fam[$famName], ([float]$px), $style, ([System.Drawing.GraphicsUnit]::Pixel)
        $ff = $fam[$famName]
        $em = $ff.GetEmHeight($style); $asc = [math]::Ceiling($px * $ff.GetCellAscent($style) / $em); $desc = [math]::Ceiling($px * $ff.GetCellDescent($style) / $em)
        $line = [int]($asc + $desc + [math]::Round($px * 0.15))
        $cw = $px * 2; $ch = $asc + $desc + 4
        $bmp = New-Object System.Drawing.Bitmap $cw, $ch
        $g = [System.Drawing.Graphics]::FromImage($bmp)
        $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
        $sf = [System.Drawing.StringFormat]::GenericTypographic
        $sf.FormatFlags = $sf.FormatFlags -bor [System.Drawing.StringFormatFlags]::MeasureTrailingSpaces
        $bits = New-Object System.Collections.Generic.List[byte]
        $glyphs = @()
        for ($c = 32; $c -le 126; $c++) {
            $s = [string][char]$c
            $g.Clear([System.Drawing.Color]::Black)
            $g.DrawString($s, $font, [System.Drawing.Brushes]::White, [float]$px * 0.5, [float]2, $sf)
            $adv = [math]::Round($g.MeasureString($s, $font, 1000, $sf).Width)
            if ($c -eq 32) { $adv = [math]::Round($px * 0.32) }
            $minx = $cw; $maxx = -1; $miny = $ch; $maxy = -1
            for ($y = 0; $y -lt $ch; $y++) { for ($x = 0; $x -lt $cw; $x++) { if ($bmp.GetPixel($x, $y).R -gt 8) { if ($x -lt $minx) { $minx = $x }; if ($x -gt $maxx) { $maxx = $x }; if ($y -lt $miny) { $miny = $y }; if ($y -gt $maxy) { $maxy = $y } } } }
            $off = $bits.Count
            if ($maxx -lt 0) { $glyphs += ,@($adv, 0, 0, 0, 0, $off); continue }
            for ($y = $miny; $y -le $maxy; $y++) { for ($x = $minx; $x -le $maxx; $x++) { $bits.Add([byte]$bmp.GetPixel($x, $y).R) } }
            $glyphs += ,@($adv, ($minx - [int]($px * 0.5)), ($miny - 2), ($maxx - $minx + 1), ($maxy - $miny + 1), $off)
        }
        $g.Dispose(); $bmp.Dispose()
        $name = "aa_${kind}_$px"
        [void]$out.Append("static const unsigned char ${name}_bits[$($bits.Count + 1)] = {")
        for ($i = 0; $i -lt $bits.Count; $i++) { if ($i % 40 -eq 0) { [void]$out.Append("`n  ") }; [void]$out.Append($bits[$i]).Append(',') }
        [void]$out.AppendLine("0};")
        [void]$out.Append("static const struct aaglyph ${name}_g[95] = {")
        foreach ($gl in $glyphs) { [void]$out.Append("{$($gl[0]),$($gl[1]),$($gl[2]),$($gl[3]),$($gl[4]),$($gl[5])},") }
        [void]$out.AppendLine("};")
        $faces += "{$px, $line, $([int]$asc + 0), $(if ($kind -eq 'bold') {1} else {0}), $(if ($kind -eq 'mono') {1} else {0}), ${name}_g, ${name}_bits}"
        $fi++
        Write-Host "$name : $($bits.Count) bytes, line $line, ascent $asc"
    }
}
[void]$out.AppendLine("static const struct aaface aa_faces[$($faces.Count)] = {")
foreach ($f in $faces) { [void]$out.AppendLine("  $f,") }
[void]$out.AppendLine('};')
[void]$out.AppendLine("#define AA_NFACES $($faces.Count)")
[IO.File]::WriteAllText((Join-Path (Split-Path -Parent $PSScriptRoot) 'font_aa.h'), $out.ToString())
